### PR TITLE
Remove issuestats

### PR DESCRIPTION
**Pull request by kubo39**
issuestats service is no longer up.

### CODE REVIEW

**Comment by wooorm** [comment]
👋

Is it really bad to keep it in here, such as for older readmes? There still seem to be [4K docs out there](https://github.com/search?q=issuestats+language%3Amarkdown&type=Code)!

**Comment by kubo39** [comment]
Thank you for the response.
I think it is not good to keep it in here since current issuestats\.com service is not badge.

**Comment by wooorm** [comment]
Removing it would be a breaking change, and would stop working with older readmes. But I don’t see why it’s really bad to have it in there? How does it hurt?

**Comment by wooorm** [comment]
@kubo39 What do you think? I’m inclined to think it’s not worth it

**Comment by wooorm** [comment]
Alright, I’ll close this. Thanks for the work, but as detailed above I don‘t see how this hurts.

**Pull request closed without merging**
